
# website settings
website:
  title: "Gina Lin"                                # Your name
  image: img/my_image.jpg
  
  favicon: img/logo.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Education and Work Experience"
        href: projects/index.qmd
      - text: "Blog"
        href: book/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: www.linkedin.com/in/ginaalin
      - icon: envelope
        aria-label: email
        href: "mailto:gina.lin1231@outlook.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Gina Lin</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true